"""
Token validation.
"""

import logging

from zope.i18nmessageid import MessageFactory
from zope.schema import TextLine

from z3c.form import button, field

from plone import api
from plone.directives import form
from plone.z3cform.layout import wrap_form

from Products.statusmessages.interfaces import IStatusMessage

from imio.googleauthenticator.helpers import drop_login_failed_msg
from imio.googleauthenticator.helpers import extract_request_data
from imio.googleauthenticator.helpers import is_account_locked
from imio.googleauthenticator.helpers import register_failed_second_factor
from imio.googleauthenticator.helpers import reset_failed_second_factor
from imio.googleauthenticator.helpers import validate_second_factor
from imio.googleauthenticator.helpers import validate_user_data

logger = logging.getLogger('imio.googleauthenticator')

DEBUG = False

_ = MessageFactory('imio.googleauthenticator')
PMF = MessageFactory('plone')


class ITokenForm(form.Schema):
    """
    Interface for the Google Authenticator Token validation form.
    """
    token = TextLine(
        title=_('Enter code'),
        description=_(
            'Enter the verification code generated by your '
            'mobile application.'),
        required=True)


class TokenForm(form.SchemaForm):
    """
    Form for the Google Authenticator Token validation. Any user that has
    two-step verification enabled, uses this form upon logging in.
    """
    fields = field.Fields(ITokenForm)
    ignoreContext = True
    schema = ITokenForm
    label = _(u'Two-step verification')
    description = _(u'Confirm your login by entering the verification code '
                    u'generated by the Google Authenticator app.')

    def action(self):
        return "{0}?{1}".format(
            self.request.getURL(),
            self.request.get('QUERY_STRING', '')
        )

    def render(self):
        """
        Inserts ``id="login_form"`` on the outer ``<form>`` tag of the
        rendered markup.

        ``plone.z3cform`` 0.8.1's ``titlelessform`` macro -- used by both
        the wrapped render path (``FormWrapper.update()``'s
        ``self.contents = self.form_instance.render()``) and the standalone
        one -- emits no ``id`` attribute on the ``<form>`` tag at all.
        Plone's own untouched overlay script (the stock
        ``plone_ecmascript/popupforms.js`` shipped by ``Products.CMFPlone``,
        no longer vendored by this package) binds its ajax overlay on a
        ``form#login_form`` selector. The form that selector must match is
        this **second**, ajax-loaded fragment -- not the stock login form
        Plone already renders correctly, which already carries that id on
        its own markup. Forking the macro to add the attribute there
        instead would re-vendor exactly the client-side code this phase
        removes, so the attribute is added here, as a post-processing step
        on the already-rendered string, and nowhere else.

        :return string: The rendered form markup, with ``id="login_form"``
            inserted on the outer ``<form>`` tag.
        """
        rendered = super(TokenForm, self).render()
        return rendered.replace('<form ', '<form id="login_form" ', 1)

    @button.buttonAndHandler(_('Verify'))
    def handleSubmit(self, action):
        """
        Here we should check couple of things:

        - If the token provided is valid.
        - If the signature contains the user data needed (username and hash
          made of his data are valid).

        If all is well and valid, we sudo login the user given.
        """

        data, errors = self.extractData()
        if errors:
            return False

        token = data.get('token', '')

        user = None
        username = self.request.get('auth_user', '')

        if username:
            user = api.user.get(username=username)

            # Validating the signed request data. If invalid (likely tampered
            # with or expired), generate an appropriate error message.
            user_data_validation_result = validate_user_data(
                request=self.request, user=user)

            if not user_data_validation_result.result:
                IStatusMessage(self.request).addStatusMessage(
                    _("Invalid data. Details: {0}".format(' '.join(
                        user_data_validation_result.reason))), 'error')
                return

            # The lock gate runs only after validate_user_data has already
            # succeeded, so an unsigned/unauthenticated caller -- one who
            # supplies nothing but a username, no password, no signature --
            # learns nothing about account lock state from this branch
            # (MFA-08's "not an oracle" half). It still runs strictly before
            # validate_token, so a locked account never reaches TOTP
            # arithmetic (MFA-08's "the lock is checked before the token is
            # evaluated" half). Do not move this gate to either side of that
            # window.
            if user is not None and is_account_locked(user):
                msg = _("Invalid token or token expired.")
                IStatusMessage(self.request).addStatusMessage(msg, 'error')
                return

        valid_token = validate_second_factor(token, user=user)

        # self.context.plone_log(valid_token)
        # self.context.plone_log(token)

        if valid_token:
            if user is not None:
                reset_failed_second_factor(user)

            # We should login the user here. `username` is typically unicode
            # (from self.request.get('auth_user', '')); str(username) would
            # implicitly encode as ASCII in Python 2 and raise
            # UnicodeEncodeError for any non-ASCII character (WR-03).
            # _setupSession accepts unicode directly on this stack.
            self.context.acl_users.session._setupSession(
                username, self.context.REQUEST.RESPONSE)

            # TODO: Is there a nicer way of resolving the
            # "@@google_authenticator_token_form" URL?
            msg = PMF("Welcome! You are now logged in.")
            IStatusMessage(self.request).addStatusMessage(msg, 'info')
            request_data = extract_request_data(self.request)
            context_url = self.context.absolute_url()
            redirect_url = request_data.get('next_url', context_url)
            self.request.response.redirect(redirect_url)
        else:
            if user is not None:
                register_failed_second_factor(user)
            msg = _("Invalid token or token expired.")
            IStatusMessage(self.request).addStatusMessage(msg, 'error')

    def updateFields(self, *args, **kwargs):
        """
        Here we clear the status messages to drop the "Login failed" message
        that appears because we consumed the credentials in our own
        IAuthenticationPlugin (after verifying the creds ourselves), and
        therefore none of the other auth plugins get a chance to log the
        user in.

        We will do that ourselves in the handleSubmit() above, but only once
        the user entered a valid token.
        """
        logger.debug("Landed in the token hook.")

        request = self.request
        response = request['RESPONSE']
        response.setCookie('__ac', '', path='/')

        # Drop the "Login failed" message that appears because we consumed
        # the credentials in our authenticator plugin.
        drop_login_failed_msg(request)

        # Updating the description
        token_field = self.fields.get('token')
        if token_field:
            token_field.field.description = _(
                'Enter the verification code generated by your mobile '
                'application. If you have somehow lost your bar code, '
                'request a bar code reset '
                '<a href=\"{0}/@@request-bar-code-reset\">here</a>.'.format(
                    self.context.absolute_url())
            )

        return super(TokenForm, self).updateFields(*args, **kwargs)


# View for the ``TokenForm``.
TokenFormView = wrap_form(TokenForm)
